доработан yaml

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -11,7 +11,6 @@ on:
       - master
       - prod
       - test
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -19,6 +18,8 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
+        with:
+          ref: main  # Укажите нужную ветку
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
@@ -33,11 +34,15 @@ jobs:
         run: |
           git fetch --all
           echo "Fetching merged branches..."
+          
           # Получаем смерженные коммиты
           MERGED_BRANCHES=$(git log --merges --pretty=format:'%s' -n 10 | grep -oP 'Merge pull request #\K[0-9]+')
 
           # Проверяем, есть ли смерженные ветки
-          if [[ -z "$MERGED_BRANCHES" ]]; then
+          if [[ $? -ne 0 ]]; then
+            echo "Error occurred while fetching merged branches."
+            MERGED_BRANCHES="None"
+          elif [[ -z "$MERGED_BRANCHES" ]]; then
             echo "No merged branches found."
             MERGED_BRANCHES="None"
           fi
@@ -47,7 +52,6 @@ jobs:
       - name: Send notification to Telegram
         if: always()
         run: |
-          # Определяем статус и соответствующий значок
           if [[ "${{ job.status }}" == "success" ]]; then
             STATUS="✅ success"
             STATUS_ICON="✅"
@@ -59,4 +63,4 @@ jobs:
           curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
             -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
             -d text="🚀 CI Build Notification%0A%0A📂 Repository: MlDwan12/investment (https://github.com/MlDwan12/investment)%0A${STATUS_ICON} Status: ${STATUS}%0A🌿 Merged branches: ${{ env.MERGED_BRANCHES }}%0A%0A🔍 *View Details* (https://github.com/MlDwan12/investment/actions/runs/${{ github.run_id }})" \
-            -d parse_mode="Markdown"
+            -d parse_mode="Markdown"s
